version: '3.8'

services:
  # Service HTTP - NGINX
  http:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./app:/app
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - script
    networks:
      - wp-network

  # Service SCRIPT - PHP-FPM
  script:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    networks:
      - wp-network

  # Service DATA - MySQL
  database_wp:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress
    ports:
      - "3306:3306"
    networks:
      - wp-network

networks:
  wp-network:
    driver: bridge

